const CDN = 'https://framerusercontent.com/images/'
const ASSET = 'https://framerusercontent.com/assets/'

export const PROJECTS = [
  {
    slug: 'how-to-change-the-world',
    title: 'HOW TO CHANGE\nTHE WORLD',
    titleCase: 'How to Change the World',
    category: 'DOCUMENTARY SERIES',
    desc: 'How To Change The World is a documentary series that explores the transformative power of social entrepreneurship. Produced by World Within Studios and Religion of Sports, with executive producers Mark Cuban, Gotham Chopra, and Geralyn Dreyfous.',
    bg: CDN + '5Tt1VWQ3pZmGknCOmCtPxUoNmss.png',
    layout: 'full',
    ticker: 'HOW TO CHANGE THE WORLD',
    details: { Type: 'Documentary Series', Producers: 'World Within Studios, Religion of Sports', 'Exec. Producers': 'Mark Cuban, Gotham Chopra, Geralyn Dreyfous' },
  },
  {
    slug: 'how-to-change-the-world-podcast',
    title: 'HOW TO CHANGE\nTHE WORLD PODCAST',
    titleCase: 'How to Change the World Podcast',
    category: 'PODCAST SERIES',
    desc: 'Produced with PRX, How to Change the World features provocative conversations with the heroes among us—mission-driven founders, artists, thought leaders, and those on the front lines building a better world.',
    bgLeft: CDN + 'gPPjhViP9TOHBXg3qtaNohUf6U.jpg',
    bgRight: CDN + 'gPPjhViP9TOHBXg3qtaNohUf6U.jpg',
    bg: CDN + 'gPPjhViP9TOHBXg3qtaNohUf6U.jpg',
    poster: '/assets/poster-podcast.jpg',
    layout: 'dual',
    ticker: 'HOW TO CHANGE THE WORLD PODCAST',
    details: { Type: 'Podcast Series', Producer: 'World Within Studios', Partner: 'PRX' },
  },
  {
    slug: 'makaylas-voice',
    title: "MAKAYLA'S VOICE:\nA LETTER TO THE WORLD",
    titleCase: "Makayla's Voice: A Letter to the World",
    category: 'A NETFLIX DOCUMENTARY FILM',
    awards: ['OSCARS® Shortlist — Best Documentary Short'],
    desc: "OSCARS® Shortlist for Best Documentary Short. A powerful portrait of a non-speaking autistic teen as she finds her voice, revealing the depth of her thoughts, creativity, and personality.",
    bg: CDN + 'b2Jl63UgEf4CqjicObjD3GNVKY.jpg',
    poster: CDN + 'uG2WjJ30JqKkatv0DXUAANpqR4g.jpg',
    trailer: 'Wm26JFhz5RE',
    layout: 'full',
    ticker: "MAKAYLA'S VOICE",
    details: { Type: 'Documentary Short Film', Platform: 'Netflix', Award: 'OSCARS® Shortlist — Best Documentary Short' },
  },
  {
    slug: 'shuffle',
    title: 'SHUFFLE',
    titleCase: 'Shuffle',
    category: 'DOCUMENTARY FILM',
    awards: ['SXSW Documentary Feature Competition Winner'],
    desc: 'SXSW Documentary Feature Competition Winner. Shuffle follows three individuals whose lives depend not on getting into treatment, but on getting out alive — shining a light on the insurance-fueled cycle of addiction treatment fraud.',
    bg: CDN + 'XJ1wyU7XTWochgfZD9DinIIlZM.jpg',
    badge: CDN + 'rpIPu4gleQg4pAXqSlmzsVSiE.png',
    poster: '/assets/poster-shuffle.png',
    trailer: 'ZNy0_Elm-Ts',
    layout: 'full',
    ticker: 'SHUFFLE',
    details: { Type: 'Documentary Feature Film', Award: 'SXSW Documentary Feature Competition Winner' },
  },
  {
    slug: 'helenibelieve',
    title: 'HELEN | BELIEVE',
    titleCase: 'Helen | Believe',
    category: 'DOCUMENTARY FILM',
    desc: "From Producer Chris Pratt, Helen | Believe follows Olympic wrestler Helen Maroulis' astonishing comeback after suffering a career-ending injury — her gripping battle with self-doubt and PTSD in pursuit of a second chance at greatness at the Tokyo Olympics.",
    bg: CDN + 'rOwXWq4vje06c3oIfJF4bHfWCoI.png',
    badge: CDN + 'pwrxWUolpplTtr7AimEgqQTurEY.svg',
    poster: CDN + 'mUoU4nK4UCH12F2FwEnQfUnDx8A.jpg',
    trailer: '_wtmiAjaIRU',
    layout: 'full',
    ticker: 'HELEN BELIEVE',
    details: { Type: 'Documentary Film', Producer: 'Chris Pratt', Subject: 'Helen Maroulis' },
  },
  {
    slug: 'bubjan',
    title: 'BUBJAN',
    titleCase: 'Bubjan',
    category: 'DOCUMENTARY SHORT',
    desc: 'Bubjan chronicles the journey of Parwiz Zafari, a former member of the Iranian parliament who dedicated his life to cultivating a progressive, modern, and free society in Iran.',
    bg: CDN + 'zeJ57yW9XjUN7uCEjUntDP8n0CY.jpg',
    poster: '/assets/poster-bubjan.jpg',
    trailer: 'dzQ3zupU4QE',
    badges: [
      CDN + 'IKjJwy5cQghynhyHeb5qHPx06g.png',
      CDN + 'G9N0cnKwN2jEW26miOcYDwNgM.png',
      CDN + 'GjvKjq658G91NEzdAXMaHBJ9Y.png',
    ],
    layout: 'full',
    ticker: 'BUBJAN',
    details: { Type: 'Documentary Short', Subject: 'Parwiz Zafari' },
  },
  {
    slug: 'river-of-spirits',
    title: 'RIVER OF\nSPIRITS',
    titleCase: 'River of Spirits',
    category: 'DOCUMENTARY FILM',
    desc: 'River of Spirits follows a group of Indigenous leaders in the heart of the Ecuadorian Amazon creating a solar revolution to save the forest and preserve their culture.',
    bg: CDN + 'oNSVvUjOxkl6fAIlbxilaha09IA.jpg',
    poster: CDN + 'LIA9yVJ2FuZLxIcXyy4wAWhYgp8.jpg',
    trailer: '/assets/trailer-river-of-spirits.mp4',
    trailerLocal: true,
    layout: 'full',
    ticker: 'RIVER OF SPIRITS',
    details: { Type: 'Documentary Short', Setting: 'Ecuadorian Amazon', Theme: 'Indigenous Rights, Solar Energy' },
  },
  {
    slug: 'voice-of-hind-rajab',
    title: 'VOICE OF\nHIND RAJAB',
    titleCase: 'Voice of Hind Rajab',
    category: 'FEATURE FILM',
    awards: ['Venice Film Festival — Grand Jury Prize'],
    desc: 'Venice Film Festival Grand Jury Prize Winner. The Voice of Hind Rajab tells the story of a 6-year-old girl trapped in a car under IDF fire in Gaza, pleading for rescue while Red Crescent volunteers do everything they can to reach her.',
    bg: CDN + 'IHrXfLs5WKKvx2lDTBbDRACe5A8.png',
    poster: CDN + 'yJZzfaAufBGPcFwe0a5rBYFUPvM.jpg',
    trailer: 'hrssPpqv6vc',
    layout: 'full',
    ticker: 'VOICE OF HIND RAJAB',
    details: { Type: 'Feature Film', Award: 'Venice Film Festival — Grand Jury Prize' },
  },
]

export const HERO_VIDEO = ASSET + 'qgKmMjCFZ2GDonZuqTZwZrKvn0.mp4'
